### ISSUE TITLE
calidad y diferentes tipos de prueba 

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-ka194#1]
[Calidad y diferentes tipos de prueba.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-ka194/files/15461582/Calidad.y.diferentes.tipos.de.prueba.pdf)

**Comment by josealfredo79** [comment]
Revisado...Calificacion 17
